---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-fake
spec:
  provider: fake-provider
  priority: 1
  size: 0
  timeout: '4h'
  state: available

---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-fallback
spec:
  provider: fake-provider
  priority: -1
  size: 0
  timeout: '4h'
  state: available

---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-libvirt
spec:
  provider: libvirt
  priority: 0
  size: 2
  timeout: '4h'
  state: available

---

apiVersion: v1
kind: Secret
metadata:
  name: cipool-libvirt-secret
type: Opaque
stringData:
  config: |
    {
      "pool": "default",
      "volume": 20,
      "backing_store": "fedora-coreos-36.20220806.3.0-qemu.x86_64.qcow2",
      "memory": 4,
      "cpus": 2,
      "bridge": "virbr0",
      "ignition": "coreos.ign"
    }

