---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-fake
spec:
  provider: fake-provider
  priority: 1
  size: 0
  timeout: '4h'
  state: available

---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-fallback
spec:
  provider: fake-provider
  priority: -1
  size: 0
  timeout: '4h'
  state: available

---

apiVersion: ofcir.openshift/v1
kind: CIPool
metadata:
  name: cipool-libvirt
spec:
  provider: libvirt
  priority: 0
  size: 2
  timeout: '4h'
  state: available

---

apiVersion: v1
kind: Secret
metadata:
  name: cipool-libvirt-secret
type: Opaque
stringData:
  config: "<tbd>"
